### ISSUE TITLE
Version 0.2.3 not tagged yet

### ISSUE THREAD

**Issue by kernandreas** [stanfy/SwiftyMock#18]
Hello together.

First I want to say thank you for the nice tool you created.

I have tried to integrate it in my project together with the Sourcery templates. I have discovered that the podspec has already the version `0.2.3` and the `Templates` subspec but the tag `0.2.3` is missing so that Cocoapods only finds version `0.2.2`

My question: Got the tag lost or is version `0.2.3` not ready yet?

Thank you!

**Comment by a-voronov** [comment]
@kernandreas it's not published yet, but I think it's ready to be

**Comment by a-voronov** [comment]
@kernandreas please check, 0.2.3 should be there :)

**Comment by kernandreas** [comment]
Thank you!

Works like a charm now!
